name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    name: Update languages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r update/requirements.txt
      - name: Run Python script
        run: |
          cd update
          python main.py
      - name: Check for changes
        run: |
          if git diff --exit-code; then
            echo "CHANGES=true" >> $GITHUB_ENV
          else
            echo "CHANGES=false" >> $GITHUB_ENV
          fi
      - name: Push changes
        if: ${{ env.CHANGES }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -a -m "Update projects"
          git push
