name: Update languages

on:
  push:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  update:
    name: Update languages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r update/requirements.txt
      - name: Retrieve environment variables
        run: |
          cd update
          touch .env
          echo PAT=${{ secrets.PAT }} >> .env
      - name: Run Python script
        run: |
          cd update
          python main.py
      - name: Check for changes
        run: |
          git status --porcelain
          if [[ `git status --porcelain` ]]; then
            echo "changes_found=true" >> $GITHUB_ENV
          else
            echo "changes_found=false" >> $GITHUB_ENV
          fi
      - name: Push changes
        if: env.changes_found == 'true'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -a -m "Update projects"
          git push
